import Head from "next/head"
import Header from "../components/Header"
import Footer from "../components/Footer"


const Layout = ({ children, title, guitarra }) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.gstatic.com"  />
                <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@200;400;500;700;900&display=swap" rel="stylesheet" />
            </Head>

            <Header
                guitarra={guitarra}
            />

            {children}

            <Footer />
        </div>
    )
}

Layout.defaultProps = {
    guitarra: null
}


export default Layout